module.exports = {
    ip : '192.168.0.110',
    DATA_EVENT_FREQUENCY: 5,


    COMPONENTS_WATER_SENSOR: 'WATER_SENSOR',
    COMPONENTS_FAN: 'FAN',

    //INPUT
    WATER_SENSOR_PIN : 2,
    LIGHT_SENSOR_PIN : 3,

    //OUTPUT
    PUMP_PIN : 7,
    FAN_PIN : 8


}