module.exports = {
    DATA_EVENT_FREQUENCY: 1,

    COMPONENTS_WATER_SENSOR: 'WATER_SENSOR',
    COMPONENTS_LIGHT_SENSOR: 'LIGHT_SENSOR',
    COMPONENTS_FAN: 'FAN',
    COMPONENTS_PUMP: 'PUMP',

    //INPUT
    LIGHT_SENSOR_PIN : 'A0',
    WATER_SENSOR_PIN : 'A1',

    TEMP_SENSOR_PIN : 5,

    //OUTPUT
    PUMP_PIN : 7,
    FAN_PIN : 8
}