module.exports = {
    SOCKET_IO_PORT : 4201,
    APP_PORT: 8080,

    SOCKET_IO_EVENT_WATER_SENSOR: '0',
    SOCKET_IO_EVENT_LIGHT_SENSOR: '1',
    SOCKET_IO_EVENT_FAN: '2',
    SOCKET_IO_EVENT_PUMP: '3'
}