module.exports = {
    SOCKET_IO_PORT : 4201,
    APP_PORT: 8080,

    SOCKET_IO_EVENT_WATER_SENSOR: 'WATER',
    SOCKET_IO_EVENT_LIGHT_SENSOR: 'LIGHT',
    SOCKET_IO_EVENT_MOISTURE_SENSOR: 'MOISTURE',
    SOCKET_IO_EVENT_TEMPERATURE_SENSOR: 'TEMP',
    SOCKET_IO_EVENT_HUMIDITY_SENSOR: 'HUMIDITY',


    SOCKET_IO_EVENT_FAN: 'FAN',
    SOCKET_IO_EVENT_PUMP: 'PUMP'
}